version: '3.4'
services:
  app:
    restart: always 
    build: 
      context: .
      dockerfile: Dockerfile
    env_file:
      - ./.env
    volumes:
      - database:/database
    ports:
      - 3000:3000
volumes:
  database: